# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-17 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='canteen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='customer_phoneNum',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='name_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='order',
            field=models.CharField(default='[]', max_length=200),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(default='Add description for this dish', max_length=100),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_type',
            field=models.CharField(default='food', max_length=20),
        ),
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dishtype_list',
            field=models.CharField(default='["food","drinks"]', max_length=200),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
