# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_auto_20180319_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='resturant',
            new_name='restaurant',
        ),
    ]
