# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-27 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_auto_20180319_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dish',
            name='nums_stars',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
