# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-27 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0004_auto_20180327_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='dish',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canteen.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Canteen'),
        ),
    ]
