# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-28 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0005_auto_20180327_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(max_length=30),
        ),
    ]
