# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-29 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0006_auto_20180328_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='nums_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
