# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-29 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0007_auto_20180329_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phoneNum', models.CharField(max_length=15)),
                ('order', models.CharField(max_length=200)),
            ],
        ),
    ]
