# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-29 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0008_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='order',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
