# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-30 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0009_auto_20180329_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='order',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
