# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-30 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0010_auto_20180330_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canteen.Canteen'),
        ),
    ]
