# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-02 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0011_conversation_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='restaurant_phoneNum',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
