# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-02 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0012_conversation_restaurant_phonenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='total_money',
            field=models.FloatField(default=0.0),
        ),
    ]
