# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-03 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0013_conversation_total_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='State',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='street_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
