# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-05 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0015_conversation_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='num',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canteen.Canteen'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
