# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-13 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0016_auto_20180405_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
