# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-04 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0017_auto_20180413_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_type',
            field=models.CharField(default='food', max_length=10),
        ),
    ]
