# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-08 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0018_dish_dish_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canteen',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='canteen',
            name='nums_stars',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='nums_stars',
        ),
        migrations.AddField(
            model_name='conversation',
            name='delivery',
            field=models.BooleanField(default=True),
        ),
    ]
