# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-11 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0020_auto_20180509_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dishtype_list',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
