# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-11 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0021_menu_dishtype_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dishtype_list',
            field=models.CharField(default='[food,drinks]', max_length=200),
        ),
    ]
