# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-21 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0025_auto_20180521_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='info',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canteen.Canteen'),
        ),
    ]
