# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-21 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0026_auto_20180521_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='name',
            field=models.CharField(default='addname', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
